// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package doctors

import (
	"database/sql"
	"time"
)

type Appointment struct {
	AppointmentID int32
	StartDate     time.Time
	EndDate       time.Time
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	PhysicianID   int32
	PatientID     int32
	NoteID        sql.NullInt32
}

type Note struct {
	NoteID    int32
	Content   sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Patient struct {
	PatientID   int32
	Name        string
	Email       string
	Cpf         string
	BirthDate   string
	PhysicianID int32
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type Physician struct {
	PhysicianID int32
	Name        string
	Email       string
	Crm         string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}
